#!/usr/bin/env python3
"""
credentials.py — LoRaWAN OTAA credentials helper for Heltec CubeCell HTCC-AB02A.

Two deployment modes:
  --write-h PATH    Write credentials into a credentials.h source file (flash via USB).
  --at-send PORT    Send credentials to the device via AT commands over serial.
                    The firmware must be compiled with AT_SUPPORT=1.
                    Requires pyserial: pip install pyserial

If no credential flags are provided, new random credentials are generated.
"""

import argparse
import random
import sys
import textwrap
import time


# ---------------------------------------------------------------------------
# Credential generation
# ---------------------------------------------------------------------------

def generate_random_hex(length: int) -> str:
    return "".join(random.choice("0123456789ABCDEF") for _ in range(length))


def create_otaa_values():
    dev_eui = generate_random_hex(16)
    app_eui = generate_random_hex(16)
    app_key = generate_random_hex(32)
    return dev_eui, app_eui, app_key


def validate_hex(value: str, expected_bytes: int, name: str) -> str:
    """Normalise and validate a hex credential (colons / dashes / spaces accepted)."""
    cleaned = value.replace(":", "").replace("-", "").replace(" ", "").upper()
    if len(cleaned) != expected_bytes * 2:
        raise ValueError(
            f"{name} must be {expected_bytes * 2} hex chars ({expected_bytes} bytes), "
            f"got {len(cleaned)}"
        )
    if not all(c in "0123456789ABCDEF" for c in cleaned):
        raise ValueError(f"{name} contains non-hex characters")
    return cleaned


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def str_to_hex_list(str_value: str) -> list:
    """Convert a hex string to a list of '0xAB' strings."""
    return [
        f"0x{str_value[i * 2]}{str_value[i * 2 + 1]}"
        for i in range(len(str_value) // 2)
    ]


def hex_to_colon(hex_str: str) -> str:
    return ":".join(hex_str[i:i + 2] for i in range(0, len(hex_str), 2))


# ---------------------------------------------------------------------------
# Arduino output
# ---------------------------------------------------------------------------

def gen_arduino_code(dev_eui: str, app_eui: str, app_key: str) -> None:
    """Print C array declarations to stdout (for reference / manual copy-paste)."""
    print(f"// dev_eui: '{dev_eui}', app_eui: '{app_eui}', app_key: '{app_key}'")
    print(f"uint8_t devEui[] = {{ {', '.join(str_to_hex_list(dev_eui))} }};")
    print(f"uint8_t appEui[] = {{ {', '.join(str_to_hex_list(app_eui))} }};")
    print(f"uint8_t appKey[] = {{ {', '.join(str_to_hex_list(app_key))} }};")


CREDENTIALS_H_TEMPLATE = """\
/**
 * LoRaWAN Credentials
 *
 * IMPORTANT: Do not commit this file to version control!
 * This file is listed in .gitignore.
 *
 * Generated by credentials.py
 * DevEUI: {dev_eui_colon}
 */

#ifndef _CREDENTIALS_H_
#define _CREDENTIALS_H_

/* OTAA parameters */
// Get these from your LoRaWAN network server (TTN, Chirpstack, etc.)
// DevEUI: {dev_eui_hex}
static uint8_t devEui[] = {{ {dev_eui_array} }};
// AppEUI: {app_eui_hex}
static uint8_t appEui[] = {{ {app_eui_array} }};
// AppKey: {app_key_hex}
static uint8_t appKey[] = {{ {app_key_array} }};


/* ABP parameters (if using ABP instead of OTAA) */
static uint8_t nwkSKey[] = {{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }};
static uint8_t appSKey[] = {{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }};
static uint32_t devAddr = (uint32_t)0x00000000;

#endif
"""


def write_credentials_h(path: str, dev_eui: str, app_eui: str, app_key: str) -> None:
    content = CREDENTIALS_H_TEMPLATE.format(
        dev_eui_colon=hex_to_colon(dev_eui),
        dev_eui_hex=dev_eui,
        app_eui_hex=app_eui,
        app_key_hex=app_key,
        dev_eui_array=", ".join(str_to_hex_list(dev_eui)),
        app_eui_array=", ".join(str_to_hex_list(app_eui)),
        app_key_array=", ".join(str_to_hex_list(app_key)),
    )
    with open(path, "w") as f:
        f.write(content)
    print(f"  Written: {path}")


# ---------------------------------------------------------------------------
# AT commands
# ---------------------------------------------------------------------------

def send_at_command(serial_conn, command: str) -> None:
    """Send a single AT command and print the response."""
    print(f"  → {command}")
    serial_conn.write(command.encode())
    time.sleep(2)
    response = serial_conn.readlines()
    for line in response:
        decoded = line.decode().strip()
        if decoded:
            print(f"  ← {decoded}")


def set_lora_parameters(serial_conn, dev_eui: str, app_eui: str, app_key: str) -> None:
    """Send the full OTAA credential sequence via AT commands.
    See: CubeCell_Series_AT_Command_User_Manual_V0.4.pdf
    """
    send_at_command(serial_conn, "AT+LPM=0")
    time.sleep(1)

    send_at_command(serial_conn, f"AT+DevEui={dev_eui}")
    time.sleep(1)

    send_at_command(serial_conn, f"AT+AppEui={app_eui}")
    time.sleep(1)

    send_at_command(serial_conn, f"AT+AppKey={app_key}")
    time.sleep(1)


def send_at_to_device(port: str, baud: int, dev_eui: str, app_eui: str, app_key: str) -> None:
    try:
        import serial
    except ImportError:
        print("Error: pyserial is required for --at-send.")
        print("Install it with:  pip install pyserial")
        sys.exit(1)

    print(f"\nConnecting to {port} at {baud} baud ...")
    try:
        with serial.Serial(port=port, baudrate=baud, dsrdtr=False, timeout=1) as ser:
            set_lora_parameters(ser, dev_eui, app_eui, app_key)
    except Exception as e:
        print(f"Error: could not open port — {e}")
        sys.exit(1)

    print("\nLoRaWAN parameters set successfully.")


# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------

def display_credentials(dev_eui: str, app_eui: str, app_key: str) -> None:
    print()
    print("Credentials")
    print("─" * 60)
    print(f"  DevEUI : {hex_to_colon(dev_eui)}")
    print(f"  AppEUI : {hex_to_colon(app_eui)}")
    print(f"  AppKey : {hex_to_colon(app_key)}")
    print("─" * 60)
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate and deploy LoRaWAN OTAA credentials for Heltec CubeCell HTCC-AB02A.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            examples:
              # Generate random credentials and write to a sketch folder
              python credentials.py --write-h mono-phase-lorawan/credentials.h

              # Write the same credentials to all three sketch folders at once
              python credentials.py \\
                --write-h mono-phase-lorawan/credentials.h \\
                --write-h three-phase-lorawan/credentials.h \\
                --write-h mono-phase-overvoltage/credentials.h

              # Use your own keys (colons optional)
              python credentials.py \\
                --deveui A8:17:58:FF:FE:0C:A6:4F \\
                --appeui 0000000000000000 \\
                --appkey AABBCCDDEEFF00112233445566778899 \\
                --write-h mono-phase-lorawan/credentials.h

              # Send credentials to a device via AT commands (requires pyserial)
              # The sketch must be compiled with LORAWAN_AT_SUPPORT ON
              python credentials.py --at-send /dev/cu.usbserial-0001
              python credentials.py --at-send COM3
        """),
    )

    cred = parser.add_argument_group(
        "credentials",
        "All optional — random values are generated when omitted.",
    )
    cred.add_argument("--deveui", metavar="HEX",
                      help="DevEUI as 16 hex chars, e.g. A81758FFFE0CA64F")
    cred.add_argument("--appeui", metavar="HEX",
                      help="AppEUI (JoinEUI) as 16 hex chars")
    cred.add_argument("--appkey", metavar="HEX",
                      help="AppKey as 32 hex chars")

    mode = parser.add_argument_group(
        "deployment mode",
        "At least one is required.",
    )
    mode.add_argument("--write-h", metavar="PATH", action="append", dest="write_h",
                      help="Write credentials.h to PATH (repeat for multiple sketch folders)")
    mode.add_argument("--at-send", metavar="PORT",
                      help="Send credentials via AT commands over serial "
                           "(e.g. /dev/cu.usbserial-0001 or COM3)")
    mode.add_argument("--baud", type=int, default=115200,
                      help="Baud rate for --at-send (default: 115200)")

    args = parser.parse_args()

    if not args.write_h and not args.at_send:
        parser.error("specify at least one of --write-h or --at-send")

    try:
        dev_eui = validate_hex(args.deveui, 8,  "DevEUI") if args.deveui else generate_random_hex(16)
        app_eui = validate_hex(args.appeui, 8,  "AppEUI") if args.appeui else generate_random_hex(16)
        app_key = validate_hex(args.appkey, 16, "AppKey") if args.appkey else generate_random_hex(32)
    except ValueError as e:
        parser.error(str(e))

    display_credentials(dev_eui, app_eui, app_key)
    gen_arduino_code(dev_eui, app_eui, app_key)
    print()

    if args.write_h:
        print("Writing credentials.h ...")
        for path in args.write_h:
            write_credentials_h(path, dev_eui, app_eui, app_key)
        print()

    if args.at_send:
        send_at_to_device(args.at_send, args.baud, dev_eui, app_eui, app_key)


if __name__ == "__main__":
    main()
